### ISSUE TITLE
Build and test instructions?

### ISSUE THREAD

**Issue by anton-trunov** [imbsky/coq-to-ocaml-to-js#5]

**Comment by smorimoto** [comment]
Is this enough? 

https://github.com/imbsky/coq-to-ocaml-to-js/blob/master/.github/workflows/workflow.yml

**Comment by smorimoto** [comment]
Well, esy is not required, if you have installed opam.

**Comment by anton-trunov** [comment]
Thanks for the pointer! Just a couple of lines in README would suffice :)

**Comment by smorimoto** [comment]
Oh, I wrote it before, but I removed it. Because this was mainly a repository to explain to my friends. But I will add it immediately!

**Comment by smorimoto** [comment]
Added in https://github.com/imbsky/coq-to-ocaml-to-js/commit/ad8ad291461fcf29f23e03423d560f9a3fd17e0d!

**Comment by anton-trunov** [comment]
Awesome!
